# This is a basic configuration file with some examples, for device mapper
# multipath.
#
# For a complete list of the default configuration values, run either
# multipath -t
# or
# multipathd show config
#
# For a list of configuration options with descriptions, see the multipath.conf
# man page

## Use user friendly names, instead of using WWIDs as names.
defaults {
    user_friendly_names yes
    find_multipaths yes
    path_checker tur
    polling_interval 10
    max_fds 8192
}
blacklist {
    # Системные и служебные устройства
    #devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
    # Все локальные SATA/SAS и NVMe диски (кроме тех, что явно нужны для мультипача)
    devnode "^sd[a-b]$"

}

blacklist_exceptions {
    device {
        vendor "TrueNAS"
        product "iSCSI Disk"
    }
    device {
        vendor "SYNOLOGY"
        product "iSCSI Storage"
    }

}

devices {
    device {
        vendor "TrueNAS"
        product "iSCSI Disk"
        path_grouping_policy failover
        path_checker directio
        no_path_retry 10
        rr_min_io_rq 1
        hardware_handler "1 alua"
    }
    device {
        vendor "SYNOLOGY"
        product "iSCSI Storage"
        path_grouping_policy failover
        path_checker directio
        no_path_retry 10
        rr_min_io_rq 1
        hardware_handler "1 alua"
    }
}
#blacklist {
#       wwid 26353900f02796769
#       devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
#       devnode "^hd[a-z]"
#}
#

